const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGNING_START: 'GOOGLE_SIGNING_START',
    GOOGLE_SIGNING_SUCCESS: 'GOOGLE_SIGNING_SUCCESS',
    GOOGLE_SIGNING_FAILURE: 'GOOGLE_SIGNING_FAILURE',
    EMAIL_SIGNING_START: 'EMAIL_SIGNING_START',
    EMAIL_SIGNING_SUCCESS: 'EMAIL_SIGNING_SUCCESS',
    EMAIL_SIGNING_FAILURE: 'EMAIL_SIGNING_FAILURE'
  };

export default UserActionTypes;